FROM mcr.microsoft.com/playwright:v1.24.0-focal
USER root
#RUN mkdir/tests
COPY . /tests
WORKDIR /tests
RUN npm install
RUN npx playwright install
RUN npx playwright install-deps
CMD npm run test
    #npx playwright test
